on: 
  watch:
    types: [started]

jobs:
  armv7_job:
    runs-on: ubuntu-18.04
    name: Build on ARMv7
    strategy:
       matrix:
         arch: [armv7, aarch64] 
    steps:
      - uses: actions/checkout@v1.0.0
      - uses: uraimo/run-on-arch-action@v1.0.7
        id: runcmd
        with:
          architecture: ${{ matrix.arch }}
          distribution: buster
          additionalArgs: <additional args for architecture specific docker, optional>
          run: |
            uname -a
            echo ::set-output name=uname::$(uname -a)
      - name: Get the output
        run: |
            echo "The uname output was ${{ steps.runcmd.outputs.uname }}"
